#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

#########################################
# 1. all spacevim option option section #
#########################################

[options]
    # set spacevim theme and colorscheme
    colorscheme = "gruvbox"
    background = "dark"
    enable_guicolors = true
    
    # set icon
    enable_os_fileformat_icon = 1
    enable_tabline_filetype_icon = 1
    
    # set statusline font/tab/mode
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_statusline_display_mode = false
    
    # set spacevim and vim compatibility
    vimcompatible = false
    
    # set relative line number
    # relativenumber = 0
    default_indent = 4
    realtime_leader_guide = 1
    enable_statusline_mode = true

    # disable ycm language completion
    # enable_ycm = true
    
    # set script for spacevim
    bootstrap_before = "myspacevim#before"


##################################
# 2. All SpaceVim plug-in config #
##################################

# find file and dir in neovim
[[layers]]
name = 'denite'

# provide tmux support
[[layers]]
name = 'tmux'

# provide git support
[[layers]]
name = 'git'

# provide git extend support 
[[layers]]
name = 'github'

# provide shell language support
[[layers]]
name = 'lang#sh'

# provide some useful tools
[[layers]]
name = 'tools'

# provide a framework for debug code
[[layers]]
name = 'debug'

# provide a framework for code completion
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

# provide markdown protocol
[[layers]]
name = 'lang#markdown'
enableWcwidth = 1
listItemIndent = 1

# provide shell command support
[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

# language server protocol 
[[layers]]
name = 'lsp'
filetypes = ["sh", "python", "javascript"]


##################################
# 3. All customer plug-in config #
##################################

# provide dispaly color support
[[custom_plugins]]
name = 'lilydjwg/colorizer'
merged = 0
